### ISSUE TITLE
Add to Cart - Falls down the screen when in browser

### ISSUE THREAD

**Issue by designzoo** [Go-Testify/thrfit_mvp#2]
The patch on the right on the product page falls down when in browser and snaps weird when scrolling.

There must be something pushing it across so it falls down.

My browser resolution is 1280 x 800

**Comment by designzoo-chris** [comment]
updated the breakpoint for browsers in the 1280 range.

**Comment by designzoo-chris** [comment]
reset position that snapping occurs, feels more natural
