### ISSUE TITLE
no account creation on purchase

### ISSUE THREAD

**Issue by designzoo** [Go-Testify/thrfit_mvp#6]
Is this agreed with Thomas. Was a bit weird that i had an account but never signed up during purchase or had the ability to choose sign up.

This may be a restriction of the shop at this point?

**Comment by designzoo** [comment]
Just got an email saying i'd created an account. Didn't think that would happen but was a nice process when i did.

**Comment by designzoo-chris** [comment]
This process is on the shopify domain, we don't have control over this text to better inform the user
